replicaCount: 1
image:
  repository: ghcr.io/paddykim/platform-observability-faulty
  tag: main@sha256:f7a257688fb64fd75bb0961637ed72b90d80a019e4bdba9c2569d1515a6a9f3d
  pullPolicy: Always
applicationName: platform-observability-faulty
failureDelaySeconds: "1.25"
service:
  port: 8000
monitoring:
  enabled: true
  labels:
    release: monitoring
  scrapeInterval: 15s
  errorRateThreshold: 0.2
  p95LatencySeconds: 1
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 192Mi
