apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-observability-faulty
  namespace: argocd
  labels:
    image-updater: enabled
  annotations:
    argocd-image-updater.argoproj.io/image-list: app=ghcr.io/paddykim/platform-observability-faulty:main
    argocd-image-updater.argoproj.io/app.update-strategy: digest
    argocd-image-updater.argoproj.io/app.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/app.helm.image-tag: image.tag
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/github-writeback
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: helmvalues:/deploy/chart/values.yaml
spec:
  project: default
  source:
    repoURL: https://github.com/paddyKim/platform-observability-faulty.git
    targetRevision: main
    path: deploy/chart
  destination:
    server: https://kubernetes.default.svc
    namespace: observability-faulty
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
